/* Automatically generated nanopb header */
/* Generated by nanopb_generator */

#ifndef PB_IOT_AIRQUALITY_AIR_QUALITY_PB_H_INCLUDED
#define PB_IOT_AIRQUALITY_AIR_QUALITY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _iot_airquality_SensorStatus {
    iot_airquality_SensorStatus_STATUS_OK = 0,
    iot_airquality_SensorStatus_STATUS_WARMING_UP = 1,
    iot_airquality_SensorStatus_STATUS_DEGRADED = 2,
    iot_airquality_SensorStatus_STATUS_FAULT = 3
} iot_airquality_SensorStatus;

/* Struct definitions */
typedef struct _iot_airquality_DeltaSample {
    uint32_t time_offset_sec;
    int32_t co2_delta_ppm;
    int32_t temp_delta_centi_deg;
    int32_t hum_delta_centi_pct;
    int32_t pm25_delta_centi_ug;
} iot_airquality_DeltaSample;

typedef struct _iot_airquality_DeltaBatch {
    pb_size_t samples_count;
    iot_airquality_DeltaSample samples[12];
} iot_airquality_DeltaBatch;

typedef struct _iot_airquality_FullSample {
    float temperature_celsius;
    float humidity_percent;
    uint32_t co2_ppm;
    float pm25_ug_m3;
    float pm10_ug_m3;
    float tvoc_ppb;
    float pressure_hpa;
} iot_airquality_FullSample;

typedef struct _iot_airquality_AirQualityPacket {
    char device_id[32];
    uint32_t sequence_number;
    uint64_t base_timestamp_sec;
    uint32_t battery_millivolts;
    int32_t rssi_dbm;
    iot_airquality_SensorStatus status;
    pb_size_t which_payload;
    union {
        iot_airquality_FullSample full_sample;
        iot_airquality_DeltaBatch delta_batch;
    } payload;
} iot_airquality_AirQualityPacket;


/* Helper constants for tables */
#define iot_airquality_SensorStatus_MIN iot_airquality_SensorStatus_STATUS_OK
#define iot_airquality_SensorStatus_MAX iot_airquality_SensorStatus_STATUS_FAULT
#define iot_airquality_SensorStatus_ARRAYSIZE ((iot_airquality_SensorStatus)(iot_airquality_SensorStatus_STATUS_FAULT+1))

#define iot_airquality_AirQualityPacket_full_sample_tag 7
#define iot_airquality_AirQualityPacket_delta_batch_tag 8

/* Struct initializers */
#define iot_airquality_FullSample_init_default   {0, 0, 0, 0, 0, 0, 0}
#define iot_airquality_DeltaSample_init_default  {0, 0, 0, 0, 0}
#define iot_airquality_DeltaBatch_init_default   {0, {iot_airquality_DeltaSample_init_default, iot_airquality_DeltaSample_init_default, iot_airquality_DeltaSample_init_default, iot_airquality_DeltaSample_init_default, iot_airquality_DeltaSample_init_default, iot_airquality_DeltaSample_init_default, iot_airquality_DeltaSample_init_default, iot_airquality_DeltaSample_init_default, iot_airquality_DeltaSample_init_default, iot_airquality_DeltaSample_init_default, iot_airquality_DeltaSample_init_default, iot_airquality_DeltaSample_init_default}}
#define iot_airquality_AirQualityPacket_init_default {"", 0, 0, 0, 0, _iot_airquality_SensorStatus_MIN, 0, {iot_airquality_FullSample_init_default}}
#define iot_airquality_FullSample_init_zero      {0, 0, 0, 0, 0, 0, 0}
#define iot_airquality_DeltaSample_init_zero     {0, 0, 0, 0, 0}
#define iot_airquality_DeltaBatch_init_zero      {0, {iot_airquality_DeltaSample_init_zero, iot_airquality_DeltaSample_init_zero, iot_airquality_DeltaSample_init_zero, iot_airquality_DeltaSample_init_zero, iot_airquality_DeltaSample_init_zero, iot_airquality_DeltaSample_init_zero, iot_airquality_DeltaSample_init_zero, iot_airquality_DeltaSample_init_zero, iot_airquality_DeltaSample_init_zero, iot_airquality_DeltaSample_init_zero, iot_airquality_DeltaSample_init_zero, iot_airquality_DeltaSample_init_zero}}
#define iot_airquality_AirQualityPacket_init_zero {"", 0, 0, 0, 0, _iot_airquality_SensorStatus_MIN, 0, {iot_airquality_FullSample_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define iot_airquality_DeltaSample_time_offset_sec_tag 1
#define iot_airquality_DeltaSample_co2_delta_ppm_tag 2
#define iot_airquality_DeltaSample_temp_delta_centi_deg_tag 3
#define iot_airquality_DeltaSample_hum_delta_centi_pct_tag 4
#define iot_airquality_DeltaSample_pm25_delta_centi_ug_tag 5
#define iot_airquality_DeltaBatch_samples_tag    1
#define iot_airquality_FullSample_temperature_celsius_tag 1
#define iot_airquality_FullSample_humidity_percent_tag 2
#define iot_airquality_FullSample_co2_ppm_tag    3
#define iot_airquality_FullSample_pm25_ug_m3_tag 4
#define iot_airquality_FullSample_pm10_ug_m3_tag 5
#define iot_airquality_FullSample_tvoc_ppb_tag   6
#define iot_airquality_FullSample_pressure_hpa_tag 7
#define iot_airquality_AirQualityPacket_device_id_tag 1
#define iot_airquality_AirQualityPacket_sequence_number_tag 2
#define iot_airquality_AirQualityPacket_base_timestamp_sec_tag 3
#define iot_airquality_AirQualityPacket_battery_millivolts_tag 4
#define iot_airquality_AirQualityPacket_rssi_dbm_tag 5
#define iot_airquality_AirQualityPacket_status_tag 6

/* Struct field encoding/decoding descriptor definitions */
extern const pb_msgdesc_t iot_airquality_FullSample_msg;
extern const pb_msgdesc_t iot_airquality_DeltaSample_msg;
extern const pb_msgdesc_t iot_airquality_DeltaBatch_msg;
extern const pb_msgdesc_t iot_airquality_AirQualityPacket_msg;

/* Defines for maximum message sizes */
#define iot_airquality_FullSample_size           35
#define iot_airquality_DeltaSample_size          30
#define iot_airquality_DeltaBatch_size           384
#define iot_airquality_AirQualityPacket_size     448

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
