/* Automatically generated nanopb constant definitions */
/* Generated by nanopb_generator */

#include "air_quality.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(iot_airquality_FullSample, iot_airquality_FullSample, AUTO)

PB_BIND(iot_airquality_DeltaSample, iot_airquality_DeltaSample, AUTO)

PB_BIND(iot_airquality_DeltaBatch, iot_airquality_DeltaBatch, AUTO)

PB_BIND(iot_airquality_AirQualityPacket, iot_airquality_AirQualityPacket, AUTO)
